# Site settings
title: jaehyun.kr
email: jaehyunkim@gmail.com
description: "Software Engineer, Entrepreneurship, Startup"
baseurl: ""
url: "http://jaehyun.kr"
twitter_username: jaehyun
github_username:  jaehyun

# Build settings
markdown: kramdown
permalink: pretty
